---
title: Blacklet
logo: img/blacklet-open.png
image: img/blacklet-open.png
description: The premium black paper notebook for creatives
url: https://blacklet.com
baseurl:
email: contact@blacklet.com
social:
- title: instagram
  url: instagram.com/theblacklet
- title: pinterest
  url: pinterest.com/theblacklet

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false