---
title: Blacklet
logo: img/Blacklet-logo.png
description: The premium black paper notebook for creatives
url: https://blacklet.com
baseurl:
email: contact@blacklet.com
social:
- title: instagram
  url: instagram.com/getblacklet
- title: pinterest
  url: pinterest.com/getblacklet

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false