---
title: Blacklet
description: The premium black paper notebook for creatives
url: https://betterlettering.com/blacklet
baseurl:
image: img/Notebook_Mockup_ISO.png
email: hello@betterlettering.com
social:
- title: instagram
  url: instagram.com/betterlettering
- title: pinterest
  url: pinterest.com/betterlettering
- title: twitter
  url: twitter.com/betterlettering
- title: facebook
  url: facebook.com/betterlettering

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false